name: Build and Test app
on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: '12.4'
      XC_WORKSPACE: 'SwiftUITryout.xcworkspace'
      XC_SCHEME: 'SwiftUITryout'
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Run Unit and UI Tests
      run:  |
        pod install
        /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
